package blps.itmo.platform.events;

public enum EventType {
    CLAIM_CREATED,
    ADDITIONAL_INFO_PROVIDED,
    ASSESSMENT_COMPLETED,
    ASSESSMENT_FAILED,
    TENANT_RESPONSE_RECEIVED,
    TENANT_RESPONSE_EXPIRED,
    CLAIM_CLOSED_NO_PENALTY,
    PENALTY_APPLICATION_REQUESTED,
    PENALTY_APPLIED,
    PENALTY_APPLICATION_FAILED,
    USER_DEACTIVATED,
    ATTACHMENT_INITIALIZED,
    ATTACHMENT_CONFIRMED,
    ATTACHMENT_BINDING_REQUESTED,
    ATTACHMENT_BOUND,
    ATTACHMENT_BINDING_FAILED,
    CLAIM_SUPPORT_REVIEW_EXPIRED
}
