services:
  postgres-business:
    image: postgres:16
    restart: unless-stopped
    container_name: blps-postgres-business
    ports:
      - "${BUSINESS_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${BUSINESS_DB_NAME}
      POSTGRES_USER: ${BUSINESS_DB_USERNAME}
      POSTGRES_PASSWORD: ${BUSINESS_DB_PASSWORD}
    volumes:
      - pgdata_business:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${BUSINESS_DB_USERNAME} -d ${BUSINESS_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-auth:
    image: postgres:16
    restart: unless-stopped
    container_name: blps-postgres-auth
    ports:
      - "${AUTH_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - pgdata_auth:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_DB_USERNAME} -d ${AUTH_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  pgdata_business:
  pgdata_auth:
  miniodata:
