package blps.itmo.claim.domain;

public enum ClaimStatus {
    ASSESSMENT_IN_PROGRESS,
    NEED_ADDITIONAL_INFO,
    AWAITING_TENANT_RESPONSE,
    SUPPORT_REVIEW,
    PENALTY_PROCESSING,
    PENALTY_APPLIED,
    PENALTY_PROCESSING_FAILED,
    CLOSED_NO_PENALTY
}
