package blps.itmo.platform.events;

public enum EventType {
    CLAIM_CREATED,
    ADDITIONAL_INFO_PROVIDED,
    ASSESSMENT_COMPLETED,
    TENANT_RESPONSE_RECEIVED,
    CLAIM_CLOSED_NO_PENALTY,
    PENALTY_APPLICATION_REQUESTED,
    PENALTY_APPLIED,
    PENALTY_APPLICATION_FAILED,
    USER_DEACTIVATED
}
