spring:
  application:
    name: claim-service
  datasource:
    url: jdbc:postgresql://localhost:5434/blps_claim
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
