package blps.itmo.claim.domain;

public enum ClaimStatus {
    SUBMITTED,
    INTAKE_REVIEW,
    NEED_ADDITIONAL_INFO,
    UNDER_ASSESSMENT,
    AWAITING_TENANT_RESPONSE,
    SUPPORT_REVIEW,
    PENALTY_PROCESSING,
    PENALTY_APPLIED,
    PENALTY_PROCESSING_FAILED,
    CLOSED_NO_PENALTY
}
