#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_DIR="$ROOT_DIR/.tmp/temporal-saga-all-states"

CLAIM_URL="${CLAIM_URL:-http://localhost:8081}"
AUTH_URL="${AUTH_URL:-http://localhost:8080}"
PENALTY_URL="${PENALTY_URL:-http://localhost:8084}"
TEMPORAL_UI="${TEMPORAL_UI:-http://localhost:8086}"

LANDLORD_ID="${LANDLORD_ID:-2}"
TENANT_ID="${TENANT_ID:-3}"
ADMIN_ID="${ADMIN_ID:-1}"

STARTED_HOLD_SECONDS="${STARTED_HOLD_SECONDS:-3}"
AWAITING_PENALTY_APPLIED_SECONDS="${AWAITING_PENALTY_APPLIED_SECONDS:-5}"
AWAITING_PENALTY_COUNTED_SECONDS="${AWAITING_PENALTY_COUNTED_SECONDS:-5}"
COMPENSATING_RETRY_SECONDS="${COMPENSATING_RETRY_SECONDS:-2}"

AUTH_PID=""
CLAIM_PID=""
PENALTY_PID=""

mkdir -p "$LOG_DIR"

log() {
  printf "\n[%s] %s\n" "$(date '+%H:%M:%S')" "$*"
}

die() {
  printf "\nERROR: %s\n" "$*" >&2
  exit 1
}

json_get() {
  local key="$1"
  python3 -c 'import json,sys; print(json.load(sys.stdin).get(sys.argv[1], ""))' "$key"
}

request() {
  local method="$1"
  local url="$2"
  local body="${3:-}"
  local output

  if [[ -n "$body" ]]; then
    output="$(curl -fsS -X "$method" "$url" \
      -H "Content-Type: application/json" \
      -H "X-User-Id: $ADMIN_ID" \
      -d "$body")"
  else
    output="$(curl -fsS -X "$method" "$url" -H "X-User-Id: $ADMIN_ID")"
  fi
  printf '%s' "$output"
}

claim_request() {
  local method="$1"
  local path="$2"
  local user_id="$3"
  local body="${4:-}"
  local output

  if [[ -n "$body" ]]; then
    output="$(curl -fsS -X "$method" "$CLAIM_URL$path" \
      -H "Content-Type: application/json" \
      -H "X-User-Id: $user_id" \
      -d "$body")"
  else
    output="$(curl -fsS -X "$method" "$CLAIM_URL$path" -H "X-User-Id: $user_id")"
  fi
  printf '%s' "$output"
}

wait_until() {
  local label="$1"
  local timeout="$2"
  local cmd="$3"
  local deadline=$((SECONDS + timeout))

  until eval "$cmd" >/dev/null 2>&1; do
    if (( SECONDS >= deadline )); then
      die "Timed out waiting for $label"
    fi
    sleep 1
  done
}

wait_http() {
  local label="$1"
  local url="$2"
  wait_until "$label" 60 "curl -fsS '$url'"
}

start_auth() {
  if [[ -n "${AUTH_PID:-}" ]] && kill -0 "$AUTH_PID" >/dev/null 2>&1; then
    return
  fi
  log "Starting auth-service on :8080"
  (cd "$ROOT_DIR" && ./gradlew :auth-service:bootRun --console=plain >"$LOG_DIR/auth-service.log" 2>&1) &
  AUTH_PID=$!
  wait_until "auth-service" 90 "curl -fsS -u tenant@blps.local:tenantpass '$AUTH_URL/api/auth/me'"
}

start_claim() {
  if [[ -n "${CLAIM_PID:-}" ]] && kill -0 "$CLAIM_PID" >/dev/null 2>&1; then
    return
  fi
  log "Starting claim-service on :8081 with short Temporal timers"
  (
    cd "$ROOT_DIR"
    ./gradlew :claim-service:bootRun --console=plain --args="\
--temporal.timeout-seconds.awaiting-penalty-applied=$AWAITING_PENALTY_APPLIED_SECONDS \
--temporal.timeout-seconds.awaiting-penalty-counted=$AWAITING_PENALTY_COUNTED_SECONDS \
--temporal.timeout-seconds.compensating-retry=$COMPENSATING_RETRY_SECONDS \
--temporal.test.started-hold-seconds=$STARTED_HOLD_SECONDS" >"$LOG_DIR/claim-service.log" 2>&1
  ) &
  CLAIM_PID=$!
  wait_http "claim-service" "$CLAIM_URL/api/claims/1"
}

start_penalty() {
  if [[ -n "${PENALTY_PID:-}" ]] && kill -0 "$PENALTY_PID" >/dev/null 2>&1; then
    return
  fi
  log "Starting penalty-service on :8084"
  (cd "$ROOT_DIR" && ./gradlew :penalty-service:bootRun --console=plain >"$LOG_DIR/penalty-service.log" 2>&1) &
  PENALTY_PID=$!
  wait_http "penalty-service" "$PENALTY_URL/api/penalties?status=APPLIED"
}

stop_pid() {
  local name="$1"
  local pid="$2"
  if [[ -n "$pid" ]] && kill -0 "$pid" >/dev/null 2>&1; then
    log "Stopping $name"
    kill "$pid" >/dev/null 2>&1 || true
    wait "$pid" >/dev/null 2>&1 || true
  fi
}

stop_auth() {
  stop_pid "auth-service" "${AUTH_PID:-}"
  AUTH_PID=""
}

stop_penalty() {
  stop_pid "penalty-service" "${PENALTY_PID:-}"
  PENALTY_PID=""
}

cleanup() {
  stop_penalty
  stop_auth
  stop_pid "claim-service" "${CLAIM_PID:-}"
}

trap cleanup EXIT

ensure_ports_free() {
  local busy=0
  for port in 8080 8081 8084; do
    if lsof -ti "tcp:$port" >/dev/null 2>&1; then
      printf "Port %s is already in use. Stop existing bootRun processes before running this script.\n" "$port" >&2
      busy=1
    fi
  done
  if [[ "$busy" == "1" ]]; then
    exit 1
  fi
}

create_claim() {
  local title="$1"
  local amount="$2"
  local response
  response="$(claim_request POST /api/claims "$LANDLORD_ID" "{
    \"tenantId\": $TENANT_ID,
    \"title\": \"$title\",
    \"description\": \"$title generated by temporal-saga-all-states.sh\",
    \"claimedAmount\": $amount,
    \"currency\": \"USD\"
  }")"
  printf '%s' "$response" | json_get id
}

drive_to_support_review() {
  local claim_id="$1"
  local amount="$2"
  claim_request POST "/api/claims/$claim_id/intake-start" "$ADMIN_ID" >/dev/null
  claim_request POST "/api/claims/$claim_id/intake-decision" "$ADMIN_ID" \
    '{"requestAdditionalInfo":false,"note":"auto"}' >/dev/null
  claim_request POST "/api/claims/$claim_id/assessment" "$ADMIN_ID" \
    "{\"penaltyGrounds\":true,\"assessmentAmount\":$amount,\"assessmentNotes\":\"auto\"}" >/dev/null
  claim_request POST "/api/claims/$claim_id/tenant-response" "$TENANT_ID" \
    '{"body":"ack"}' >/dev/null
}

support_decision() {
  local claim_id="$1"
  local amount="$2"
  local simulate_failure="$3"
  local response
  response="$(claim_request POST "/api/claims/$claim_id/support-decision" "$ADMIN_ID" "{
    \"applyPenalty\": true,
    \"penaltyAmount\": $amount,
    \"penaltyCurrency\": \"USD\",
    \"simulateFailure\": $simulate_failure,
    \"resolutionNote\": \"automated Temporal state coverage\"
  }")"
  printf '%s' "$response" | json_get currentSagaId
}

new_saga() {
  local label="$1"
  local amount="$2"
  local simulate_failure="${3:-false}"
  local claim_id saga_id

  claim_id="$(create_claim "$label" "$amount")"
  drive_to_support_review "$claim_id" "$amount"
  saga_id="$(support_decision "$claim_id" "$amount" "$simulate_failure")"
  printf '%s:%s' "$claim_id" "$saga_id"
}

get_saga_state() {
  local saga_id="$1"
  request GET "$CLAIM_URL/api/sagas/$saga_id" | json_get state
}

expect_state() {
  local label="$1"
  local saga_id="$2"
  local expected="$3"
  local timeout="$4"
  local deadline=$((SECONDS + timeout))
  local state=""

  while (( SECONDS < deadline )); do
    state="$(get_saga_state "$saga_id" || true)"
    if [[ "$state" == "$expected" ]]; then
      printf "OK %-30s %-28s %s\n" "$label" "$expected" "penalty-application-$saga_id"
      return
    fi
    sleep 1
  done
  die "$label expected $expected, last observed state=$state, saga=$saga_id"
}

print_workflow() {
  local label="$1"
  local saga_id="$2"
  printf "%-30s %s\n" "$label" "penalty-application-$saga_id"
}

main() {
  command -v curl >/dev/null || die "curl is required"
  command -v python3 >/dev/null || die "python3 is required for JSON parsing"
  command -v docker >/dev/null || die "docker is required"
  command -v lsof >/dev/null || die "lsof is required"

  ensure_ports_free

  log "Starting infrastructure"
  (cd "$ROOT_DIR" && docker compose up -d kafka kafka-ui minio postgres-auth postgres-claim postgres-penalty postgres-temporal temporal temporal-ui jira)

  start_auth
  start_claim
  start_penalty

  log "Test 1: STARTED -> COMPLETED"
  IFS=: read -r claim_completed saga_completed < <(new_saga "Temporal auto COMPLETED" 80 false)
  expect_state "started marker/query" "$saga_completed" STARTED "$((STARTED_HOLD_SECONDS + 2))"
  expect_state "happy path" "$saga_completed" COMPLETED 30

  log "Test 2: PENALTY_FAILED"
  IFS=: read -r claim_failed saga_failed < <(new_saga "Temporal auto PENALTY_FAILED" 90 true)
  expect_state "business failure" "$saga_failed" PENALTY_FAILED 30

  log "Test 3: AWAITING_PENALTY_COUNTED -> COMPENSATED"
  stop_auth
  IFS=: read -r claim_compensated saga_compensated < <(new_saga "Temporal auto COMPENSATED" 110 false)
  expect_state "waiting for auth-service" "$saga_compensated" AWAITING_PENALTY_COUNTED 30
  expect_state "compensated timeout" "$saga_compensated" COMPENSATED 40

  log "Test 4: AWAITING_PENALTY_APPLIED -> COMPENSATING_REVOKE -> COMPENSATION_FAILED"
  stop_penalty
  IFS=: read -r claim_comp_failed saga_comp_failed < <(new_saga "Temporal auto COMPENSATION_FAILED" 120 false)
  expect_state "waiting for penalty-service" "$saga_comp_failed" AWAITING_PENALTY_APPLIED 30
  expect_state "compensation started" "$saga_comp_failed" COMPENSATING_REVOKE 30
  expect_state "compensation failed" "$saga_comp_failed" COMPENSATION_FAILED 40

  log "Temporal workflows to inspect at $TEMPORAL_UI"
  print_workflow "STARTED/COMPLETED" "$saga_completed"
  print_workflow "PENALTY_FAILED" "$saga_failed"
  print_workflow "AWAITING_COUNTED/COMPENSATED" "$saga_compensated"
  print_workflow "AWAITING_APPLIED/COMP_FAILED" "$saga_comp_failed"

  log "All requested SagaState values were observed through /api/sagas/{id}."
  log "In Temporal UI, open each workflow History and look for MarkerRecorded values like saga-state=STARTED, saga-state=AWAITING_PENALTY_APPLIED, etc."
}

main "$@"
