spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://${NOTIFICATION_DB_HOST:localhost}:${NOTIFICATION_DB_PORT:5437}/${NOTIFICATION_DB_NAME:blps_notification}
    username: ${NOTIFICATION_DB_USERNAME:blps_notification_user}
    password: ${NOTIFICATION_DB_PASSWORD:blps_notification_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

server:
  port: ${NOTIFICATION_SERVICE_PORT:8085}

app:
  service-name: notification-service
  outbox:
    poll-interval-ms: 1000
