DROP TABLE IF EXISTS claim_attachments CASCADE;
DROP TABLE IF EXISTS claim_status_history CASCADE;
DROP TABLE IF EXISTS claim_messages CASCADE;
DROP TABLE IF EXISTS claims CASCADE;

DROP TYPE IF EXISTS attachmentpurpose CASCADE;
DROP TYPE IF EXISTS commenttype CASCADE;
DROP TYPE IF EXISTS claimstatus CASCADE;
