BEGIN;

DROP TABLE IF EXISTS role_privileges CASCADE;
DROP TABLE IF EXISTS privileges CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS outbox_events CASCADE;
DROP TABLE IF EXISTS processed_messages CASCADE;

DROP TYPE IF EXISTS userrole;

COMMIT;
