DROP TABLE IF EXISTS claim_attachments CASCADE;
DROP TABLE IF EXISTS claim_status_history CASCADE;
DROP TABLE IF EXISTS claim_messages CASCADE;
DROP TABLE IF EXISTS claims CASCADE;
DROP TABLE IF EXISTS role_privileges CASCADE;
DROP TABLE IF EXISTS privileges CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS attachmentpurpose CASCADE;
DROP TYPE IF EXISTS commenttype CASCADE;
DROP TYPE IF EXISTS claimstatus CASCADE;
DROP TYPE IF EXISTS userrole CASCADE;
